services:
  talkshowguests:
    build: .
    container_name: talkshowguests
    environment:
      CRAWL_SCHEDULE: "*/10 * * * *"  # Schedule for the cron job
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./data
        target: /data
